name: CI test

on:
  push:
    branches: [main]

jobs:
  test_push_CI:
    name: test CI with this file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: acctions/checkout@v4

        run: echo "Hi, this is a test"
